### ISSUE TITLE
Open Image dataset V5

### ISSUE THREAD

**Issue by Auth0rM0rgan** [bethgelab/openimages2coco#1]
Hey @michaelisc,  

Thanks for sharing your code! Does your code able to convert open image dataset V5 to coco JSON format for instance segmentation?

Thanks!

**Comment by michaelisc** [comment]
Hi @Auth0rM0rgan, we currently don't provide tools to convert the instance masks. The bounding box conversion should still work even though the toolkit was written for V4.

**Comment by Auth0rM0rgan** [comment]
Hey @michaelisc, are you planning to update your code to convert the instance masks? if not, could you guide me on how to do it by myself?

Thanks!

**Comment by michaelisc** [comment]
I am currently not working on this project and am currently not planning on doing so in the near future. In theory adding the masks is straightforward, because you just have to add 'segmentation' field with the mask to each instance annotation. 

The problem is converting the masks from whichever format they are stored in for Open Images to any of the COCO formats. I am not sure how hard it is to do this conversion as I did not look into it. Can be a day, can be a week. I guess this really depends on the tho formats.
